# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df152be35fab5cd0b2f22df0cc0e37be22431489ad09fc5c94657952b721f7d5e4f64a5dcd2fbf2d8b5f6405b5671dbbe0669ad1772f7340f75092f5ea1744e

test:
  secret_key_base: 6932df183132bef8c0e28a28f1095ca6e568befa125dbf47ab9568dcea2041131513723e052683e3b8303a0be29f3e0f977b525c1312e45f55c19348d532556b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
